package com.springboot.riot.api.contents.common.dto


data class SummonerMatchDto (
    var accountId: String? = null,
    var activityNm: String? = null,
    var activityKorNm: String? = null,
    var classification: Int = 0,
    var classificationNm: String? = null,
    var teamSeq: Int = 0,
    var teamNm: String? = null,
    var teamKorNm: String? = null,
    var mostLane: Int = 0,
    var mostLaneNm: String? = null,
    var userName: String? = null,
    var gameId: Long = 0L,
    var platformId: String? = null,
    var champion: Int = 0,
    var queue: Int = 0,
    var queueNm: String? = null,
    var season: Int = 0,
    var timeStamp: Long = 0L,
    var lane: String? = null,
    var gameDuration: Int = 0,
    var enemyChampion: Int = 0,
    var spell1: Int = 0,
    var spell2: Int = 0,
    var perkPrimaryStyle: Int = 0,
    var perkSubStyle: Int = 0,
    var teamId: Int = 0,
    var participantId: Int = 0,
    var win: Boolean = false,
    var kills: Int = 0,
    var deaths: Int = 0,
    var assists: Int = 0,
    var item0: Int = 0,
    var item1: Int = 0,
    var item2: Int = 0,
    var item3: Int = 0,
    var item4: Int = 0,
    var item5: Int = 0,
    var item6: Int = 0,

)

