package com.springboot.riot.api.contents.detail.dto

data class ParticipantDto(
    val participantId: Int = 0,
    val teamId: Int = 0,
    val championId: Int = 0,
    val spell1Id: Int = 0,
    val spell2Id: Int = 0,
    val platformId: String? = null,
    val accountId: String? = null,
    val summonerName: String? = null,
    val profileIcon: Int = 0,
    val win: Boolean = false,
    val item0: Int = 0,
    val item1: Int = 0,
    val item2: Int = 0,
    val item3: Int = 0,
    val item4: Int = 0,
    val item5: Int = 0,
    val item6: Int = 0,
    val kills: Int = 0,
    val deaths: Int = 0,
    val assists: Int = 0,
    val totalDamageDealt: Int = 0,
    val goldEarned: Int = 0,
    val turretKills: Int = 0,
    val totalMinionsKilled: Int = 0,
    val neutralMinionsKilled: Int = 0,
    val champLevel: Int = 0,
    val visionWardsBoughtIngame: Int = 0,
    val sightWardsBoughtIngame: Int = 0,
    val wardsPlaced: Int = 0,
    val wardsKilled: Int = 0,
)
